### ISSUE TITLE
要自己实现重试机制吗？

### ISSUE THREAD

**Issue by tanteng** [Latrell/Lock#3]
请问一下，如果请求发现上了锁，这个时候是会立即返回异常，还是会自动阻塞等待解锁呢？要自己实现重试机制吗？

**Comment by tanteng** [comment]
![image](https://user-images.githubusercontent.com/3405598/54998666-ab471180-5009-11e9-854b-b0d3b61a00cb.png)
从这个配置看，应该是阻塞一段时间，等待超时

**Comment by latrell** [comment]
会阻塞，直到锁超时。需要自己实现重试。
